p4 edit ..\Content\JavaScript\PuertsEditor\...
..\..\..\..\..\Engine\Binaries\ThirdParty\Nodejs\Win64\node.exe .\node_modules\typescript\bin\tsc -p .\tsconfig.json
p4 revert -a ..\Content\JavaScript\PuertsEditor\...

